# Actualizaciones automáticas
options:
  auto-update: true

# Mundo habilitado o deshabilitado
worlds:
- disabled_world

# lista blanca (whitelist) o lista negra (blacklist) ，El valor predeterminado es el modo de lista negra
world-filter-type: blacklist

# mecanismo
mechanics:
  # incendio forestal
  FOREST_FIRES:
    # Ya sea para habilitar
    enabled: true
    # probabilidad (0-1)
    chance: 0.3
    # velocidad de propagación de la llama
    fire-per-second: 10
    # Temperatura mínima de activación (Celsius）
    min-temperature-in-celsius: 40.0
  # glaciares derritiéndose
  ICE_MELTING:
    # Ya sea para habilitar
    enabled: true
    # probabilidad (0-1)
    chance: 0.5
    # velocidad de fusión
    melt-per-second: 10
    # Temperatura mínima de activación (Celsius）
    min-temperature-in-celsius: 2.0
  # desacelerar
  SLOWNESS:
    # Ya sea para habilitar
    enabled: true
    # probabilidad (0-1)
    chance: 0.8
  # combustión
  BURN:
    # Ya sea para habilitar
    enabled: true
    # probabilidad
    chance: 0.8

# Investigación preliminar que debe desbloquearse para realizar investigaciones sobre el calentamiento global
needed-research-for-player-mechanics: ENERGY_REGULATOR

# Configuración de contaminación
# Relacionado con la máquinaIDPuedes sostener la máquina en el juego y usar comandos./sf idConsulta
# artículo originalID: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
pollution:
  # generación de contaminación
  production:
    # Contaminación causada por la entrada de la máquina.
    machine-recipe-input-items:
      CHARCOAL: 0.0025
      COAL: 0.005
      CARBON: 0.01
      COMPRESSED_CARBON: 0.013
      CARBON_CHUNK: 0.015
      SYNTHETIC_DIAMOND: 0.015
      RAW_CARBONADO: 0.017
      CARBONADO: 0.02
      BUCKET_OF_OIL: 0.015
      NETHER_ICE: 0.02
      URANIUM: 0.02
      BLISTERING_INGOT: 0.025
      BLISTERING_INGOT_2: 0.027
      BLISTERING_INGOT_3: 0.03
    # Contaminación causada por el funcionamiento de las máquinas.
    machines:
      COAL_GENERATOR: 0.001
      COAL_GENERATOR_2: 0.0015
      NUCLEAR_REACTOR: 0.03
      COMBUSTION_REACTOR: 0.015
    # Contaminación por alimentar a los animales.
    animal-breed: 0.005
  # absorción de contaminación
  absorption:
    # máquina de absorción de contaminación
    machines:
      AIR_COMPRESSOR: 0.05
    # plantar arboles
    tree-growth: 0.005

# Opciones de temperatura
temperature-options:
  pollution-multiply: 0.002
  temperature-drop-during-storms: 8
